const commodityList = {
  0: [
    { title: '苹果数据线' },
    { title: '安卓数据线' },
    { title: '抽纸' },
    { title: '插座' },
    { title: '衣架' },
    { title: '1个' },
    { title: '放在门口' },
    { title: '挂在门把手上' },
    { title: '慢慢送不着急' },
    { title: '辛苦了' },
    { title: '谢谢' }
  ],
  1: [
    { title: '可乐' },
    { title: '雪碧' },
    { title: '红牛' },
    { title: '矿泉水' },
    { title: '冰的' },
    { title: '热的' },
    { title: '1瓶' },
    { title: '1杯' },
    { title: '无糖' },
    { title: '放在门口' },
    { title: '挂在门把手上' },
    { title: '慢慢送不着急' },
    { title: '辛苦了' },
    { title: '谢谢' }
  ],
  2: [
    { title: 'KFC全家桶' },
    { title: '水饺' },
    { title: '瘦肉丸' },
    { title: '烧饼' },
    { title: '泡面' },
    { title: '披萨' },
    { title: '蛋糕' },
    { title: '炒粉' },
    { title: '炒饭' },
    { title: '烤猪蹄' },
    { title: '瓜子' },
    { title: '1份' },
    { title: '放在门口' },
    { title: '挂在门把手上' },
    { title: '慢慢送不着急' },
    { title: '辛苦了' },
    { title: '谢谢' }
  ],
  3: [
    { title: '圆珠笔' },
    { title: '中性笔' },
    { title: '铅笔' },
    { title: '钢笔' },
    { title: '橡皮' },
    { title: '尺子' },
    { title: '练习簿' },
    { title: '笔记本' },
    { title: '1支' },
    { title: '1本' },
    { title: '放在门口' },
    { title: '挂在门把手上' },
    { title: '慢慢送不着急' },
    { title: '辛苦了' },
    { title: '谢谢' }
  ],
  4: [
    { title: '1点点' },
    { title: 'CoCo' },
    { title: '古茗' },
    { title: '茶百道' },
    { title: '喜茶' },
    { title: '厝内小眷村' },
    { title: '蜜雪冰城' },
    { title: '1杯' },
    { title: '正常糖' },
    { title: '无糖' },
    { title: '去冰' },
    { title: '热饮' },
    { title: '放在门口' },
    { title: '挂在门把手上' },
    { title: '慢慢送不着急' },
    { title: '辛苦了' },
    { title: '谢谢' }
  ],
  5: [
    { title: '止泻药' },
    { title: '胃药' },
    { title: '过敏药' },
    { title: '999感冒灵' },
    { title: '放在门口' },
    { title: '挂在门把手上' },
    { title: '慢慢送不着急' },
    { title: '辛苦了' },
    { title: '谢谢' }
  ],
  6: [
    { title: '啤酒' },
    { title: '白酒' },
    { title: '红酒' },
    { title: '二锅头' },
    { title: '青岛' },
    { title: '燕京' },
    { title: '百威' },
    { title: '江小白' },
    { title: '威士忌' },
    { title: '伏特加' },
    { title: '1瓶' },
    { title: '1罐' },
    { title: '冰的' },
    { title: '开瓶器' },
    { title: '放在门口' },
    { title: '挂在门把手上' },
    { title: '慢慢送不着急' },
    { title: '辛苦了' },
    { title: '谢谢' }
  ],
  7: [
    { title: '苹果' },
    { title: '香蕉' },
    { title: '草莓' },
    { title: '车厘子' },
    { title: '火龙果' },
    { title: '橘子' },
    { title: '梨' },
    { title: '生菜' },
    { title: '萝卜' },
    { title: '1斤' },
    { title: '放在门口' },
    { title: '挂在门把手上' },
    { title: '慢慢送不着急' },
    { title: '辛苦了' },
    { title: '谢谢' }
  ],
  99: [
    { title: '无接触配送' },
    { title: '放在门口' },
    { title: '挂在门把手上' },
    { title: '到了电话联系' },
    { title: '注意安全' },
    { title: '慢慢送不着急' },
    { title: '辛苦了' },
    { title: '谢谢' }
  ],
}
export { commodityList };